app/urls.py
from django.urls import path
from app import views

app_name='app'

urlpatterns=[
    path('sree/',views.sree,name='sree')

]

urlnavigation/urls.py
from django.contrib import admin
from django.urls import path,include

from app import views

import app

urlpatterns = [
    path('admin/', admin.site.urls),
    path('saran/',views.saran,name='saran'),
    path('logi/',views.logi,name='logi'),
    path('app/',include('app.urls'))
]

app/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render

# Create your views here.


def saran(request):
    return render(request,'one.html')

def logi(request):
    return render(request,'two.html')

def sree(request):
    return render(request,'three.html')

templates/one.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>First file</title>
</head>
<body>
    <h1>First file</h1>
    <h2>Hi im Saravanan</h2>
    <h3><a href='{% url "logi" %}' target='_blank'>Goto Second File</a></h3>
    <hr>
    <h3><a href='{% url "app:sree" %}' target='_blank'>Goto Third File</a></h3>
</body>
</html>

templates/three.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Third File</title>
</head>
<body>
    <h1>Third file</h1>
    <h2>Hi, im Sree</h2>
    <h3><a href='{% url "saran" %}' target='_blank'>Goto First File</a></h3>
    <hr>
    <h3><a href='{% url "logi" %}' target='_blank'>Goto Second File</a></h3>
</body>
</html>

templates/two.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Second File</title>
</head>
<body>
    <h1>Second file</h1>
    <h2>Hi im Logesh</h2>
    <h3><a href='{% url "saran" %}' target='_blank'>Goto First File</a></h3>
    <hr>
    <h3><a href='{% url "app:sree" %}' target='_blank'>Goto Third File</a></h3>
</body>
</html>